### ISSUE TITLE
Endpoint for Resized Images

### ISSUE THREAD

**Issue by nomadstays** [stevetemple/Image-Resizer-Azure-Function#2]
At the risk of embarrassing myself for lack of technical skills... where do I find the newly resized images?

As an example, here is a source image file on Azure Storage: 
https://nomadstays.blob.core.windows.net/nomadstays/img/homepage/1476-namibia-1920.jpg

Where would I go to get an image resized to 1000px width?

Am expecting the tail end would be something like  .../img/homepage/1476-namibia-1920.jpg?width=1000

The new CacheContainer is currently empty although the app reported to install OK.

**Comment by stevetemple** [comment]
Sorry, just noticed this,

You point the resizer at the container then you'll go to the new functions URL 

https://<func-url>/api/img/homepage/1476-namibia-1920.jpg?width=100&height=100
